### ISSUE TITLE
dependencies in python packages broke

### ISSUE THREAD

**Issue by sebag90** [clp-research/slurk#255]
dependencies in python packages broke and as a result slulrk no longer works.
Error in the logs

```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.9/site-packages/socketio/server.py", line 733, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/usr/local/lib/python3.9/site-packages/socketio/server.py", line 758, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/usr/local/lib/python3.9/site-packages/flask_socketio/__init__.py", line 283, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.9/site-packages/flask_socketio/__init__.py", line 751, in _handle_event
    ret = handler(*args)
  File "/usr/src/slurk/views/chat/events.py", line 23, in room_created
    socketio.emit("new_room", {"room": room.id}, broadcast=True)
  File "/usr/local/lib/python3.9/site-packages/flask_socketio/__init__.py", line 461, in emit
    self.server.emit(event, *args, namespace=namespace, room=room,
TypeError: emit() got an unexpected keyword argument 'broadcast'
2023-03-18T19:00:24Z <Thread at 0x7fa228d937c0: <bound method Server._handle_event_internal of <socketio.server.Server object at 0x7fa22a000c10>>(<socketio.server.Server object at 0x7fa22a000c10>, 'wOIhyyToT8ubjCm4AAAB', 'mWf-DNbga56ouMfTAAAA', ['room_created', {'room': 2, 'task': 1}], '/', None)> failed with TypeError

[2023-03-18 19:00:24,920] DEBUG in __init__: loading user from id 3
```

**Comment by janagoetze** [comment]
needs to be revisited to keep packes up-to-date

**Comment by sebag90** [comment]
the culprit seems to be `python-socketio==5.8`; adding `python-socketio==5.7.2` explicitly to the requirements list solves this issue
